# Generated by Django 4.0 on 2021-12-30 12:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('chronic_diseases', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('data', models.DateField(blank=True, null=True)),
                ('isAuthenticated', models.BooleanField(default=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
