# Generated by Django 4.0 on 2022-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doner_blood_type_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='https://www.clipartmax.com/png/small/96-967482_hemoglobin-enables-red-blood-cells-to-carry-oxygen-red-blood-cell-png.png', upload_to='image'),
        ),
    ]
