# Generated by Django 4.0 on 2021-12-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
