# Generated by Django 4.0 on 2022-01-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_donate_account_location_alter_account_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.RemoveField(
            model_name='account',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='account',
            name='data',
        ),
        migrations.RemoveField(
            model_name='account',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isAuthenticated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
