# Generated by Django 4.0 on 2022-01-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('Doner', 'Doner'), ('Hospital', 'Hospital'), ('Patient', 'Patient')], max_length=50, null=True),
        ),
    ]
