# Generated by Django 4.0 on 2022-01-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
    ]
