# Generated by Django 4.0 on 2022-01-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donating', '0002_post_donation'),
        ('accounts', '0006_remove_doner_blood_type_remove_patient_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='blood_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blood_donating.bloodtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blood_donating.bloodtype'),
            preserve_default=False,
        ),
    ]
