# Generated by Django 4.0 on 2022-01-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('accounts', '0006_alter_customuser_address_alter_doner_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Address.address'),
        ),
    ]
