# Generated by Django 4.0 on 2022-01-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_address'),
        ('accounts', '0007_doner_blood_type_patient_blood_type'),
    ]

    operations = [
    ]
